services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis:7.2.2
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/data/db
